export const brandLevels = {
  Barrett: 'Premium',
  'Bravo Company': 'Mid-Range',
  Brownells: 'Mid-Range',
  'Century Arms': 'Mid-Range',
  'Aero Precision': 'Mid-Range',
  'American Arms': 'Mid-Range',
  Andersen: 'Budget',
  Benelli: 'Premium',
  Beretta: 'Mid-Range',
  Bergara: 'Premium',
  'Black Rain': 'Mid-Range',
  'Centurion Arms': 'Mid-Range',
  Chiappa: 'Mid-Range',
  'Dan Wesson': 'Premium',
  'American Tactical Imports': 'Mid-Range',
  'Double Star': 'Mid-Range',
  'Ed Brown': 'Premium',
  'F-1 Firearms': 'Premium',
  Faxon: 'Premium',
  'Fn America': 'Premium',
  Geissele: 'Premium',
  'Heckler & Koch': 'Premium',
  HENRY: 'Mid-Range',
  'Heritage Arms': 'Mid-Range',
  Savage: 'Mid-Range',
  Seekins: 'Premium',
  'Sig Sauer': 'Mid-Range',
  'Smith & Wesson': 'Mid-Range',
  "Spike's Tactical": 'Mid-Range',
  Springfield: 'Mid-Range',
  'Steyr Arms (Steyr Mannlicher)': 'Mid-Range',
  Stoeger: 'Mid-Range',
  Taurus: 'Budget',
  Thompson: 'Mid-Range',
  Walther: 'Mid-Range',
  Windham: 'Premium',
  'Yankee Hill Machine Co': 'Premium',
  Zastava: 'Mid-Range',
  'Brigand Arms Llc': 'Mid-Range',
  Browning: 'Mid-Range',
  Canik: 'Mid-Range',
  'Charter Arms': 'Mid-Range',
  Colt: 'Mid-Range',
  'Cz-Usa': 'Mid-Range',
  'Daniel Defense': 'Premium',
  Diamondback: 'Mid-Range',
  Glock: 'Mid-Range',
  'Hi-Point': 'Budget',
  'Iwi Us': 'Mid-Range',
  'Kel-Tec': 'Mid-Range',
  Kimber: 'Premium',
  LWRCI: 'Premium',
  'Palmetto State Armory': 'Budget',
  'Patriot Ordnance Factory': 'Premium',
  'Rock Island': 'Budget',
  Ruger: 'Mid-Range',
  'Sds Imports': 'Mid-Range',
  SCCY: 'Budget',
  MOSSBERG: 'Mid-Range',
  CENTURY: 'Mid-Range',
  WEATHERBY: 'Premium',
  TIKKA: 'Premium',
  'KEYSTONE SPORTING ARM': 'Budget',
  CHRISTENSEN: 'Mid-Range',
  ROSSI: 'Budget',
  Crickett: 'Budget',
  HOWA: 'Mid-Range',
  'Pioneer Arms': 'Mid-Range',
  REMINGTON: 'Mid-Range',
  'ZRO DELTA': 'Mid-Range',
  'North Star Arms': 'Mid-Range',
  WINCHESTER: 'Mid-Range',
  'ROCK RIVER ARMS': 'Mid-Range',
}

export const alphabets = [
  '#',
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
]
